<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('ZF2 '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/images/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()->prependFile($this->basePath() . '/js/jquery-1.11.1.min.js')
                                        ->prependFile($this->basePath() . '/js/bootstrap.min.js')
                                        ->prependFile($this->basePath() . '/js/teste.js')?>
    </head>
    <body>
        <div>
            <ul>
                <li><a href="<?php echo $this->url('application') ?>">TODOS</a></li>
                <li><a href="<?php echo 'application/index/alocado' ?>">ALOCADOS</a></li>
                <li><a href="<?php echo $this->url('application', array('action' => 'recebido')) ?>">RECEBIDOS</a></li>
                <li><a href="<?php echo $this->url('application', array('action' => 'suspenso')) ?>">SUSPENSOS</a></li>
                <li><a href="<?php echo $this->url('application', array('action' => 'fechado')) ?>">FECHADOS</a></li>
            </ul>
        </div>
        <div class="container">
            <?php echo $this->content; ?>
            <hr>
            <footer>
                <p>&copy; 2005 - 2012 by Zend Technologies Ltd. <?php echo $this->translate('All rights reserved.') ?></p>
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
